<?php
$page           = (!empty($_GET['page-id']) && is_numeric($_GET['page-id'])) ? Secure($_GET['page-id']) : 1;
$db->pageLimit  = 20;
$mediafiles = $db->objectbuilder()->orderBy('id', 'DESC')->paginate('mediafiles', $page);

if (($page > $db->totalPages) && !empty($_GET['page-id'])) {
    header("Location: " . Wo_LoadAdminLinkSettings('manage-photos'));
    exit();
}

?>
<div class="container-fluid">
    <div class="block-header">
        <h2>Photos > Manage Photos & Videos</h2>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h2>Manage Photos & Videos</h2>
                    
                </div>
                <div class="clearfix"></div>
                <div class="table-responsive1">
                    <table class="table table-bordered table-striped table-hover">
                        <tbody>
                        <?php
                        foreach ($mediafiles as $mediafilelist) {
                            $wo['mediafilelist'] = $mediafilelist;
                            $wo['mediafilelist']->user->avater->avater = GetMedia($user['avater']);
                            echo Wo_LoadAdminPage('manage-photos/list');
                        }
                        ?>
                        </tbody>
                    </table>
                </div>
               
</div>



<script>

    function Wo_DeletePhoto(photo_id,photo_file) {
        if (confirm("Are you sure you want to delete this photo?") == false) {
            return false;
        }
        hash_id = '<?php echo Wo_CreateSession();?>';
        $('#PhotoID_' + photo_id).fadeOut(300, function() {
            $(this).remove();
        });
        $.get(Wo_Ajax_Requests_File(),{f:'admin_setting', s:'delete_photo', p: 'manage-photos', photo_id: photo_id, photo_file: photo_file, hash_id: hash_id});
    }

    function Wo_ApprovePhoto(photo_id,photo_file) {
        hash_id = '<?php echo Wo_CreateSession();?>';
        $('#mediafile_' + photo_id).fadeOut(300, function() {
            $(this).remove();
        });
        $.get(Wo_Ajax_Requests_File(),{f:'admin_setting', s:'approve_photo', p: 'manage-photos', photo_id: photo_id, photo_file: photo_file, hash_id: hash_id}, function (data) {
            if(data.status == 200){
                window.location.reload();
            }
        });
    }

    function Wo_DisApprovePhoto(photo_id,photo_file) {
        hash_id = '<?php echo Wo_CreateSession();?>';
        $('#mediafile_' + photo_id).fadeOut(300, function() {
            $(this).remove();
        });
        $.get(Wo_Ajax_Requests_File(),{f:'admin_setting', s:'disapprove_photo', p: 'manage-photos', photo_id: photo_id, photo_file: photo_file, hash_id: hash_id}, function (data) {
            if(data.status == 200){
                window.location.reload();
            }
        });
    }


    function Wo_ApproveAllPhoto() {
        if (confirm("Are you sure you want to Approve all media files?") == false) {
            return false;
        }
        hash_id = '<?php echo Wo_CreateSession();?>';
        $.get(Wo_Ajax_Requests_File(),{f:'admin_setting', s:'approve_all_photo', p: 'manage-photos', hash_id: hash_id}, function (data) {
            if(data.status == 200){
                window.location.reload();
            }
        });
    }

    function Wo_DisApproveAllPhoto() {
        if (confirm("Are you sure you want to DisApprove all media files?") == false) {
            return false;
        }
        hash_id = '<?php echo Wo_CreateSession();?>';
        $.get(Wo_Ajax_Requests_File(),{f:'admin_setting', s:'disapprove_all_photo', p: 'manage-photos', hash_id: hash_id}, function (data) {
            if(data.status == 200){
                window.location.reload();
            }
        });
    }




</script>